from enum import Enum, auto

class ActionType(Enum):
    NONE = auto()
    MOVE_UP = auto()
    MOVE_DOWN = auto()
    MOVE_LEFT = auto()
    MOVE_RIGHT = auto()
    INTERACT_UP = auto()
    INTERACT_DOWN = auto()
    INTERACT_LEFT = auto()
    INTERACT_RIGHT = auto()
    INTERACT_CENTER = auto()
    SELECT_SLOT_0 = auto()
    SELECT_SLOT_1 = auto()
    SELECT_SLOT_2 = auto()
    SELECT_SLOT_3 = auto()
    SELECT_SLOT_4 = auto()
    SELECT_SLOT_5 = auto()
    SELECT_SLOT_6 = auto()
    SELECT_SLOT_7 = auto()
    SELECT_SLOT_8 = auto()
    SELECT_SLOT_9 = auto()
    PLACE_ITEM_UP = auto()
    PLACE_ITEM_DOWN = auto()
    PLACE_ITEM_LEFT = auto()
    PLACE_ITEM_RIGHT = auto()